name: Schedule heartbeat

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: date -u
      - name: Heartbeat check
        run: echo "Heartbeat at $(date -u)"
